package sintef.android.controller;

/**
 * Created by samyboy89 on 29/01/15.
 */
public enum EventTypes {
    ONRESUME,
    ONPAUSE,
    ONDESTROY,
    ONSTOP,
    FINISH,
    FALL_DETECTED,
    RESET_SENSOR_LISTENERS,
    START_ALARM,
    STOP_ALARM,
    ALARM_STOPPED,
    ADVANCED_MODE_CHANGED,

    TEST_FALL,
    TEST_NO_FALL,

    RECORDING_PHONE_TOTAL_ACCELERATION,
    RECORDING_PHONE_VERTICAL_ACCELERATION,
    RECORDING_WATCH_FALL_INDEX,
    RECORDING_WATCH_DIRECTION_ACCELERATION,
    RECORDING_WATCH_AFTER_FALL,
}
