package sintef.android.controller.sensor;

import android.hardware.Sensor;

/**
 * Created by samyboy89 on 03/02/15.
 */
public enum SensorType {
    ACCELEROMETER(Sensor.TYPE_ACCELEROMETER),
    AMBIENT_TEMPERATURE(Sensor.TYPE_AMBIENT_TEMPERATURE),
    GAME_ROTATION_VECTOR(Sensor.TYPE_GAME_ROTATION_VECTOR),
    GEOMAGNETIC_ROTATION_VECTOR(Sensor.TYPE_GEOMAGNETIC_ROTATION_VECTOR),
    GRAVITY(Sensor.TYPE_GRAVITY),
    GYROSCOPE(Sensor.TYPE_GYROSCOPE),
    GYROSCOPE_UNCALIBRATED(Sensor.TYPE_GYROSCOPE_UNCALIBRATED),
    HEART_RATE(Sensor.TYPE_HEART_RATE),
    LIGHT(Sensor.TYPE_LIGHT),
    LINEAR_ACCELERATION(Sensor.TYPE_LINEAR_ACCELERATION),
    MAGNETIC_FIELD(Sensor.TYPE_MAGNETIC_FIELD),
    MAGNETIC_FIELD_UNCALIBRATED(Sensor.TYPE_MAGNETIC_FIELD_UNCALIBRATED),
    ORIENTATION(Sensor.TYPE_ORIENTATION),
    PRESSURE(Sensor.TYPE_PRESSURE),
    PROXIMITY(Sensor.TYPE_PROXIMITY),
    RELATIVE_HUMIDITY(Sensor.TYPE_RELATIVE_HUMIDITY),
    ROTATION_VECTOR(Sensor.TYPE_ROTATION_VECTOR),
    SIGNIFICANT_MOTION(Sensor.TYPE_SIGNIFICANT_MOTION),
    STEP_COUNTER(Sensor.TYPE_STEP_COUNTER),
    STEP_DETECTOR(Sensor.TYPE_STEP_DETECTOR),
    TEMPERATURE(Sensor.TYPE_TEMPERATURE);

    private int mType;

    SensorType(int type) {
        mType = type;
    }

    public int getType() {
        return mType;
    }
}
